# Generated by Django 3.2 on 2022-09-14 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_original', models.TextField()),
                ('txt_translation', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(10, 'In Queue'), (20, 'In Process'), (30, 'Translated'), (40, 'Checking'), (50, 'Checked')], default=10)),
                ('qa_comment', models.TextField(blank=True, null=True)),
                ('user_qa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qas', to=settings.AUTH_USER_MODEL)),
                ('user_translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_move_from_10_to_20', 'Can move from In Queue to In Process'), ('can_move_from_10_to_30', 'Can move from In Queue to Translated'), ('can_move_from_10_to_40', 'Can move from In Queue to Checking'), ('can_move_from_10_to_50', 'Can move from In Queue to Checked'), ('can_move_from_20_to_10', 'Can move from In Process to In Queue'), ('can_move_from_20_to_30', 'Can move from In Process to Translated'), ('can_move_from_20_to_40', 'Can move from In Process to Checking'), ('can_move_from_20_to_50', 'Can move from In Process to Checked'), ('can_move_from_30_to_10', 'Can move from Translated to In Queue'), ('can_move_from_30_to_20', 'Can move from Translated to In Process'), ('can_move_from_30_to_40', 'Can move from Translated to Checking'), ('can_move_from_30_to_50', 'Can move from Translated to Checked'), ('can_move_from_40_to_10', 'Can move from Checking to In Queue'), ('can_move_from_40_to_20', 'Can move from Checking to In Process'), ('can_move_from_40_to_30', 'Can move from Checking to Translated'), ('can_move_from_40_to_50', 'Can move from Checking to Checked'), ('can_move_from_50_to_10', 'Can move from Checked to In Queue'), ('can_move_from_50_to_20', 'Can move from Checked to In Process'), ('can_move_from_50_to_30', 'Can move from Checked to Translated'), ('can_move_from_50_to_40', 'Can move from Checked to Checking'), ('can_change_translation', 'Can Change Translation'), ('can_change_qa_comment', 'Can Change QA Comment')],
            },
        ),
    ]
