# Generated by Django 3.2 on 2022-09-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
